package com.application.enums;

public enum Nationality {
	AFGHAN, ALBANIAN, ALGERIAN, AMERICAN, ANDORRAN, ANGOLAN, ANTIGUAN_AND_BARBUDAN, ARGENTINE, ARMENIAN, ARUBAN,
	AUSTRALIAN, AUSTRIAN, AZERBAIJANI, BAHAMIAN, BAHRAINI, BANGLADESHI, BARBADIAN, BASQUE, BELARUSIAN, BELGIAN,
	BELIZEAN, BENINESE, BERMUDIAN, BHUTANESE, BOLIVIAN, BOSNIAK, BOSNIAN_AND_HERZEGOVINIAN, BOTSWANA, BRAZILIAN, BRETON,
	BRITISH, BRITISH_VIRGIN_ISLANDER, BRUNEIAN, BULGARIAN, MACEDONIAN_BULGARIAN, BURKINABÉ, BURMESE, BURUNDIAN,
	CAMBODIAN, CAMEROONIAN, CANADIAN, CATALAN, CAPE_VERDEAN, CHALDEAN, CHADIAN, CHILEAN, CHINESE, COLOMBIAN, COMORIAN,
	CONGOLESE_DRC, CONGOLESE_ROTC, COSTA_RICANS, CROAT, CUBAN, CYPRIOT, CZECH, DANE, GREENLANDER, DJIBOUTIAN,
	DOMINICAN_COMMONWEALTH, DOMINICAN_REPUBLIC, DUTCH, EAST_TIMORESE, ECUADORIAN, EGYPTIAN, EMIRATI, ENGLISH,
	EQUATOGUINEANS, ERITREAN, ESTONIAN, ETHIOPIAN, FALKLAND_ISLANDER, FAROESE, FIJIAN, FINN, FINNISH, SWEDISH, FILIPINO,
	FRENCH_CITIZEN, GABONES, GAMBIAN, GEORGIAN, GERMAN, BALTIC_GERMAN, GHANAIAN, GIBRALTARIAN, GREEK, GREEK_MACEDONIAN,
	GRENADIAN, GUATEMALAN, GUYANESE, HAITIAN, HONDURAN, HONG_KONGER, HUNGARIAN, ICELANDER, I_KIRIBATI, INDIAN,
	INDONESIAN, IRANIAN, IRAQI, IRISH, ISRAELI, ITALIAN, IVOIRIAN, JAMAICAN, JAPANESE, JORDANIAN, KAZAKH, KENYAN,
	KOREAN, KOSOVAR, KUWAITI, KYRGYZ, LAO, LATVIAN, LEBANESE, LIBERIAN, LIBYAN, LIECHTENSTEINER, LITHUANIAN,
	LUXEMBOURGER, MACAO, MACEDONIAN, MALAGASY, MALAWIAN, MALAYSIAN, MALDIVIAN, MALIAN, MALTESE, MANX, MARSHALLESE,
	MAURITANIAN, MAURITIAN, MEXICAN, MICRONESIAN, MOLDOVAN, MONÉGASQUE, MONGOLIAN, MONTENEGRIN, MOROCCAN, MOZAMBICAN,
	NAMIBIAN, NAURUAN, NEPALESE, NEW_ZEALANDER, NICARAGUAN, NIGERIEN, NIGERIAN, NORWEGIAN, OMANI, PAKISTANI, PALAUAN,
	PALESTINIAN, PANAMANIAN, PAPUA_NEW_GUINEAN, PARAGUAYAN, PERUVIAN, POLE, PORTUGUESE, PUERTO_RICAN, QATARI, QUEBECER,
	RÉUNIONNAI, ROMANIAN, RUSSIAN, BALTIC_RUSSIAN, RWANDAN, SAINT_KITT_AND_NEVI, SAINT_LUCIAN, SALVADORAN, SAMMARINESE,
	SAMOAN, SÃO_TOMÉ_AND_PRÍNCIPE, SAUDI, SCOT, SENEGALESE, SERB, SEYCHELLOI, SIERRA_LEONEAN, SINGAPOREAN, SLOVAK,
	SLOVENE, SOLOMON_ISLANDER, SOMALI, SOMALILANDER, SOTHO, SOUTH_AFRICAN, SPANIARD, SRI_LANKAN, SUDANESE, SURINAMESE,
	SWAZI, SWEDE, SWISS, SYRIAC, SYRIAN, TAIWANESE, TAMIL, TAJIK, TANZANIAN, THAI, TIBETAN, TOBAGONIAN, TOGOLESE,
	TONGAN, TRINIDADIAN, TUNISIAN, TURK, TUVALUAN, UGANDAN, UKRAINIAN, URUGUAYAN, UZBEK, VANUATUAN, VENEZUELAN,
	VIETNAMESE, VINCENTIAN, WELSH, YEMENI, ZAMBIAN, ZIMBABWEAN;

}
